<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE ciudades [
    <!ELEMENT ciudades (ciudad)+>
    <!ELEMENT ciudad (nombre, pais)>
    <!ATTLIST ciudad continente NMTOKENS #REQUIRED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT pais (#PCDATA)>
]>

<ciudades>
    <ciudad continente="Asia">
        <nombre>Nueva Delhi</nombre>
        <pais>India</pais>
    </ciudad>
    <ciudad continente="Europa">
        <nombre>Lisboa</nombre>
        <pais>Portugal</pais>
    </ciudad>
    <ciudad continente="Africa">
        <nombre>El Cairo</nombre>
        <pais>Egipto</pais>
    </ciudad>
</ciudades>