<?xml version="1.0" encoding="UTF-8"?>

<!-- control + A seleccionar todo -->
<!-- alt + shift + f tabular todo -->
<!-- control + รง comentar -->

<!-- Personas que constituyen un colegio, 
tenemos un alumno con un nombre y que cursa 
dos tipos de asignaturas, un profesor y un director. -->

<!DOCTYPE persona [
    <!ELEMENT persona (alumno, profesor, director)>
    <!ELEMENT alumno (nombre,asignatura)>
    <!ELEMENT asignatura (programacion, ofimatica)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT programacion (#PCDATA)>
    <!ELEMENT ofimatica (#PCDATA)>
    <!ELEMENT profesor (#PCDATA)>
    <!ELEMENT director (#PCDATA)>
]>

<persona>
    <alumno>
        <nombre>Jose Menendez</nombre>
        <asignatura>
            <programacion>LM</programacion>
            <ofimatica>Excel Avanzado</ofimatica>
        </asignatura>
    </alumno>
    <profesor>Maria Rodriguez</profesor>
    <director>Pedro Perez</director>
</persona>