<?xml version="1.0" encoding="UTF-8"?>


<!-- Unos programadores necesitan estructurar la 
    información que intercambiarán los ficheros de
sus aplicaciones para lo cual han determinado los 
requisitos siguientes.

Los ficheros deben tener un elemento <listafacturas>
Dentro de la lista debe haber una o más facturas.

Las facturas tienen un atributo fecha que es optativo.

Toda factura tiene un emisor , que es un elemento 
obligatorio y que debe tener un
atributo cif (el emisor) que es obligatorio. Dentro 
de emisor debe haber un elemento nombre , que
es obligatorio y puede o no haber un elemento 
volumenventas .

Toda factura debe tener un elemento pagador , 
el cual tiene exactamente la misma
estructura que emisor .

Toda factura tiene un elemento importe . -->


<!DOCTYPE listaFacturas[
    <!ELEMENT listaFacturas (facturas+)>
    <!ATTLIST facturas fecha (2022|2023) #IMPLIED>
    <!ELEMENT facturas (emisor, pagador, importe)>
    <!ATTLIST emisor cif NMTOKEN #REQUIRED>
    <!ELEMENT emisor (nombre, volumenVentas?)>
    <!ATTLIST pagador cif NMTOKENS #REQUIRED>
    <!ELEMENT pagador (nombre, volumenVentas?)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT volumenVentas (#PCDATA)>
    <!ELEMENT importe (#PCDATA)>
]>


<listaFacturas>

    <facturas fecha="2023">
        <emisor cif="hola_mundo">
            <nombre></nombre>
        </emisor>
        <pagador cif="hola mundo">
            <nombre></nombre>
            <volumenVentas></volumenVentas>
        </pagador>
        <importe></importe>
    </facturas>
</listaFacturas>
