<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE figuras [
    <!ELEMENT figuras (figura)+>
    <!ELEMENT figura (nombre, lados?, aristas?, caras?)>
    <!ATTLIST figura tipo NMTOKENS #REQUIRED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT lados (#PCDATA)>
    <!ELEMENT aristas (#PCDATA)>
    <!ELEMENT caras (#PCDATA)>
]>

<figuras>
  <figura tipo = "plana">
    <nombre>cuadrado</nombre>
    <lados>4</lados>
  </figura>
  <figura tipo = "plana">
    <nombre>tri√°ngulo</nombre>
    <lados>3</lados>
  </figura>
  <figura tipo = "tridimensional">
    <nombre>cubo</nombre>
    <aristas>12</aristas >
    <caras>6</caras>
  </figura>
</figuras>